export * from './company/base'
export * from './people/house'
export * from './people/info'
export * from './selfemployed/base'
export * from './selfemployed/house'
export * from './selfemployed/info'
export * from './selfemployed/equipment'
